services:
  api:
    build: .
    container_name: skalla-api
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    expose:
      - "8000"
    networks:
      - skalla-network

  db:
    image: postgres:16
    container_name: skalla-db
    restart: always
    environment:
      POSTGRES_USER: skalla
      POSTGRES_PASSWORD: skalla123
      POSTGRES_DB: skalla
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - skalla-network

  nginx:
    image: nginx:alpine
    container_name: skalla-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - api
    networks:
      - skalla-network

volumes:
  postgres_data:

networks:
  skalla-network:
    driver: bridge
